import React from 'react';
import { Link } from 'react-router-dom';

const CookiesPolicyPage = () => {
  // Scroll to top when component mounts
  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="max-w-4xl mx-auto mt-8 p-6 bg-white dark:bg-gray-800 rounded-lg shadow-md">
      <h1 className="text-2xl font-bold mb-6 text-center">Cookies Policy</h1>
      
      <div className="prose prose-lg dark:prose-invert max-w-none">
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">Last Updated: September 14th, 2025</p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Introduction</h2>
        <p>
          This Cookies Policy explains what cookies are and how Doughmination System™ ("we", "us", or "our") uses them on our website. 
          We encourage you to read this policy in order to understand what types of cookies we use, what information we collect 
          using cookies, and how that information is used.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">What Are Cookies?</h2>
        <p>
          Cookies are small text files that are stored on your computer or mobile device when you visit a website. 
          They allow the website to recognize your device and remember if you've been to the website before. 
          Cookies are a very common web technology; most websites use cookies and have done so for years. 
          Cookies are widely used to make websites work more efficiently and provide valuable information to website owners.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Types of Cookies We Use</h2>
        <p>We use different types of cookies for various reasons:</p>
        
        <h3 className="text-lg font-semibold mt-4 mb-2">Essential Cookies</h3>
        <p>
          These cookies are necessary for the website to function properly. They enable core functionality such as security, 
          network management, and accessibility. You may disable these by changing your browser settings, but this may affect 
          how the website functions.
        </p>
        
        <h3 className="text-lg font-semibold mt-4 mb-2">Performance Cookies</h3>
        <p>
          These cookies help us to understand how visitors interact with our website by collecting and reporting information anonymously. 
          They help us understand which pages are the most and least popular and see how visitors move around the site.
        </p>
        
        <h3 className="text-lg font-semibold mt-4 mb-2">Functionality Cookies</h3>
        <p>
          These cookies enable the website to provide enhanced functionality and personalization. 
          They may be set by us or by third-party providers whose services we have added to our pages.
        </p>
        
        <h3 className="text-lg font-semibold mt-4 mb-2">Targeting Cookies</h3>
        <p>
          These cookies record your visit to our website, the pages you have visited, and the links you have followed. 
          We will use this information to make our website and the advertising displayed on it more relevant to your interests. 
          We may also share this information with third parties for this purpose.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Third-Party Cookies</h2>
        <p>
          In addition to our own cookies, we may also use various third-party cookies to report usage statistics of the website 
          and deliver advertisements on and through the website. The third-party services we use include:
        </p>
        
        <h3 className="text-lg font-semibold mt-4 mb-2">Google Services</h3>
        <p>
          We use Google Analytics to help analyze how users use the Site. Google Analytics uses cookies to collect standard 
          internet log information and visitor behavior information in an anonymous form. The information generated by the cookie 
          about your use of the website (including IP address) is transmitted to Google.
        </p>
        <p>
          We also use Google AdSense to display advertisements. Google AdSense is a program run by Google that allows publishers 
          in the Google Network of content sites to serve automatic text, image, video, or interactive media advertisements.
        </p>
        <p>
          For more information on how Google uses data when you use our Site, please visit Google's Privacy Policy:
          <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline ml-1">https://policies.google.com/privacy</a>
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Managing Cookies</h2>
        <p>
          Most web browsers allow you to manage your cookie preferences. You can set your browser to refuse cookies, 
          or to alert you when cookies are being sent. The following links show how to adjust the browser settings of commonly used browsers:
        </p>
        <ul className="list-disc ml-6 mb-4">
          <li>
            <a href="https://support.google.com/chrome/answer/95647?hl=en" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Chrome</a>
          </li>
          <li>
            <a href="https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?redirectslug=enable-and-disable-cookies-website-preferences&redirectlocale=en-US" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Firefox</a>
          </li>
          <li>
            <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Safari</a>
          </li>
          <li>
            <a href="https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Edge</a>
          </li>
        </ul>
        <p>
          Please note that if you choose to refuse cookies, you may not be able to use the full functionality of our website.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Our Consent Management Platform</h2>
        <p>
          We use a Consent Management Platform (CMP) that allows you to choose which cookies you allow us to use. 
          When you first visit our website, you'll be presented with a cookie banner that allows you to:
        </p>
        <ul className="list-disc ml-6 mb-4">
          <li>Accept all cookies</li>
          <li>Decline non-essential cookies</li>
          <li>Manage your preferences in detail</li>
        </ul>
        <p>
          You can change your preferences at any time by clicking on the "Cookie Settings" link in the footer of our website.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Changes to This Cookie Policy</h2>
        <p>
          We may update our Cookie Policy from time to time. We will notify you of any changes by posting the new Cookie Policy 
          on this page and updating the "Last Updated" date at the top of this Cookie Policy.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-4">Trademarks</h2>
        <p>
          "Doughmination System" is a pending trademark in the United Kingdom under trademark number UK00004263144.
        </p>
        
        <h2 className="text-xl font-semibold mt-6 mb-4">Contact Us</h2>
        <p>If you have any questions about our Cookie Policy, please contact us:</p>
        <ul className="list-disc ml-6 mb-4">
          <li>Email: admin@clovetwilight3.co.uk</li>
        </ul>
      </div>
      
      <div className="mt-8 pt-4 border-t dark:border-gray-700">
        <Link to="/" className="text-blue-500 dark:text-blue-400 hover:underline">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
};

export default CookiesPolicyPage;