name: Build All Websites

on:
  workflow_dispatch:

jobs:
  dough-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Clear Docker builder cache
        run: docker builder prune -af || true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Doughmination Backend
        uses: docker/build-push-action@v6
        with:
          context: ./doughmination.win/backend
          file: ./doughmination.win/backend/Dockerfile
          push: true
          tags: clovetwilight3/doughmination-backend:latest
          no-cache: true

  dough-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Doughmination Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./doughmination.win/frontend
          file: ./doughmination.win/frontend/Dockerfile
          push: true
          tags: clovetwilight3/doughmination-frontend:latest
          no-cache: true

  midnightcyan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build The Midnight Cyan
        uses: docker/build-push-action@v6
        with:
          context: ./themidnightcyan.win
          file: ./themidnightcyan.win/Dockerfile
          push: true
          tags: clovetwilight3/themidnightcyan:latest
          no-cache: true

  estrogen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build EstrogenHRT Gaming
        uses: docker/build-push-action@v6
        with:
          context: ./mazeymoos.com
          file: ./mazeymoos.com/Dockerfile
          push: true
          tags: clovetwilight3/estrogen-moos:latest
          no-cache: true

  butterfly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Butterfly Network
        uses: docker/build-push-action@v6
        with:
          context: ./butterfly-network.win
          file: ./butterfly-network.win/Dockerfile
          push: true
          tags: clovetwilight3/butterfly-network:latest
          no-cache: true

  lgbwitht:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build LGB with T
        uses: docker/build-push-action@v6
        with:
          context: ./lgbwitht.win
          file: ./lgbwitht.win/Dockerfile
          push: true
          tags: clovetwilight3/lgb-with-t:latest
          no-cache: true

  nytrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Clove Nytrix
        uses: docker/build-push-action@v6
        with:
          context: ./alextlm.co.uk
          file: ./alextlm.co.uk/Dockerfile
          push: true
          tags: clovetwilight3/clove-nytrix:latest
          no-cache: true
