name: Build EstrogenHRT Gaming

on:
  push:
    branches: [main]
    paths:
      - 'mazeymoos.com/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./mazeymoos.com
          file: ./mazeymoos.com/Dockerfile
          push: true
          tags: clovetwilight3/estrogen-moos:latest
          no-cache: true
