name: Build Status Frontend

on:
  push:
    branches: [main]
    paths:
      - 'status.butterfly-network.win/frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./status.butterfly-network.win/frontend
          file: ./status.butterfly-network.win/frontend/Dockerfile
          push: true
          tags: clovetwilight3/status-frontend:latest
          no-cache: true
